using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using ClearVision.Product.Core.Attributes;
using ClearVision.Product.Core.Enums;

namespace ClearVision.Product.Core.Services;

[Obsolete("Use ImageContractAdmission and ImageContractVerification. This compatibility enum cannot express admission and evidence independently.")]
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ImageContractStatus
{
    Native,
    Converted,
    Restricted,
    Rejected,
    Unknown
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ImageContractAdmission
{
    Allowed,
    Rejected,
    Unknown
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ImageContractVerification
{
    VerifiedSupport,
    VerifiedConversion,
    LegacyCompatibilityAllowance,
    VerifiedRejection,
    Unknown
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ImageContractInputValuePolicy
{
    Any,
    RejectNonFinite,
    RequireFiniteFloat32Representable
}

[Obsolete("Use ImageContractVariant. This compatibility type cannot represent exact depth/channel pairs without one entry per pair.")]
public sealed record ImageModeRestriction(
    string Mode,
    ImageContractStatus Status,
    IReadOnlyList<string> SupportedDepths,
    IReadOnlyList<int> SupportedChannels,
    string ConversionPolicy,
    string OutputDepthPolicy,
    string DynamicRangePolicy,
    string FailureCode,
    string EvidenceLevel,
    string? Condition = null);

public sealed record ImageContractVariant(
    string Mode,
    string Depth,
    int Channels,
    string Condition,
    ImageContractAdmission Admission,
    ImageContractVerification Verification,
    string ConversionPolicy,
    string OutputDepthPolicy,
    string DynamicRangePolicy,
    ImageContractInputValuePolicy InputValuePolicy,
    string FailureCode,
    string EvidenceLevel);

[method: JsonConstructor]
public sealed record ImageInputContract(
    string InputPort,
    IReadOnlyList<string> SupportedDepths,
    IReadOnlyList<int> SupportedChannels,
    IReadOnlyList<string> NativeDepths,
    string InputDepthPolicy,
    string ImplicitConversionPolicy,
    string OutputDepthPolicy,
    string DynamicRangePolicy,
    IReadOnlyList<ImageContractVariant> Variants,
    string NonFinitePolicy,
    string FailureCode,
    string ContractVersion)
{
    [JsonIgnore]
    public ImageInputContractPresentation Presentation => ImageContractPresentationBuilder.Build(this);

    [Obsolete("Use Variants and inspect Admission/Verification independently.")]
    [JsonIgnore]
    public ImageContractStatus Status => ImageContractCompatibilityAdapter.GetLegacyStatus(Variants);

    [Obsolete("Use Variants. ModeRestrictions cannot model exact depth/channel pairs without ambiguity.")]
    [JsonIgnore]
    public IReadOnlyList<ImageModeRestriction> ModeRestrictions =>
        ImageContractCompatibilityAdapter.GetLegacyRestrictions(Variants);

    [Obsolete("Evidence is variant-specific. Use Variants or Presentation.ExactVariantGroups.")]
    [JsonIgnore]
    public string EvidenceLevel => ImageContractCompatibilityAdapter.GetLegacyEvidenceLevel(Variants);

    [Obsolete("Use the constructor that accepts exact ImageContractVariant entries.")]
    public ImageInputContract(
        string inputPort,
        IReadOnlyList<string> supportedDepths,
        IReadOnlyList<int> supportedChannels,
        IReadOnlyList<string> nativeDepths,
        string inputDepthPolicy,
        string implicitConversionPolicy,
        string outputDepthPolicy,
        string dynamicRangePolicy,
        IReadOnlyList<ImageModeRestriction> modeRestrictions,
        string nonFinitePolicy,
        string failureCode,
        string contractVersion,
        ImageContractStatus status,
        string evidenceLevel)
        : this(
            inputPort,
            supportedDepths,
            supportedChannels,
            nativeDepths,
            inputDepthPolicy,
            implicitConversionPolicy,
            outputDepthPolicy,
            dynamicRangePolicy,
            ImageContractCompatibilityAdapter.ToExactVariants(
                supportedDepths,
                supportedChannels,
                modeRestrictions,
                status,
                implicitConversionPolicy,
                outputDepthPolicy,
                dynamicRangePolicy,
                failureCode,
                evidenceLevel),
            nonFinitePolicy,
            failureCode,
            contractVersion)
    {
    }

    [Obsolete("Use the exact-variant Deconstruct overload generated by the current record shape.")]
    public void Deconstruct(
        out string inputPort,
        out IReadOnlyList<string> supportedDepths,
        out IReadOnlyList<int> supportedChannels,
        out IReadOnlyList<string> nativeDepths,
        out string inputDepthPolicy,
        out string implicitConversionPolicy,
        out string outputDepthPolicy,
        out string dynamicRangePolicy,
        out IReadOnlyList<ImageModeRestriction> modeRestrictions,
        out string nonFinitePolicy,
        out string failureCode,
        out string contractVersion,
        out ImageContractStatus status,
        out string evidenceLevel)
    {
        inputPort = InputPort;
        supportedDepths = SupportedDepths;
        supportedChannels = SupportedChannels;
        nativeDepths = NativeDepths;
        inputDepthPolicy = InputDepthPolicy;
        implicitConversionPolicy = ImplicitConversionPolicy;
        outputDepthPolicy = OutputDepthPolicy;
        dynamicRangePolicy = DynamicRangePolicy;
        modeRestrictions = ModeRestrictions;
        nonFinitePolicy = NonFinitePolicy;
        failureCode = FailureCode;
        contractVersion = ContractVersion;
        status = Status;
        evidenceLevel = EvidenceLevel;
    }
}

public sealed record ImageContractVariantPresentation(
    string Mode,
    string Condition,
    ImageContractAdmission Admission,
    ImageContractVerification Verification,
    IReadOnlyList<string> ExactInputTypes,
    string ConversionPolicy,
    string OutputDepthPolicy,
    string DynamicRangePolicy,
    ImageContractInputValuePolicy InputValuePolicy,
    string FailureCode,
    string EvidenceLevel);

public sealed record ImageInputContractPresentation(
    string InputPort,
    string ContractVersion,
    int AllowedVariantCount,
    int VerifiedSupportVariantCount,
    int VerifiedConversionVariantCount,
    int LegacyCompatibilityVariantCount,
    int VerifiedRejectionVariantCount,
    int UnknownVariantCount,
    bool HasProductionSupport,
    bool CompatibilityOnly,
    string EvidenceSummary,
    IReadOnlyList<ImageContractVariantPresentation> ExactVariantGroups);

public sealed record OperatorImageContractPresentationSummary(
    int ContractCount,
    int AllowedVariantCount,
    int VerifiedSupportVariantCount,
    int VerifiedConversionVariantCount,
    int LegacyCompatibilityVariantCount,
    int VerifiedRejectionVariantCount,
    int UnknownVariantCount,
    bool HasProductionSupport,
    bool CompatibilityOnly,
    string EvidenceSummary);

public sealed record ImageContractCompactVariantGroup(
    IReadOnlyList<string> Modes,
    IReadOnlyList<string> Inputs,
    string When,
    ImageContractAdmission Admission,
    ImageContractVerification Verification,
    string Convert,
    string Output,
    string Range,
    ImageContractInputValuePolicy Values,
    string Failure,
    string Evidence);

public sealed record ImageInputContractCompactPresentation(
    string Port,
    string Version,
    string EvidenceSummary,
    int VerifiedSupport,
    int VerifiedConversion,
    int Compatibility,
    int Rejection,
    int Unknown,
    IReadOnlyList<ImageContractCompactVariantGroup> Variants);

public sealed record ImageContractModeCase(
    IReadOnlyList<string> Inputs,
    ImageContractAdmission Admission,
    ImageContractVerification Verification,
    string Failure,
    string Evidence);

public sealed record ImageContractModeGroup(
    IReadOnlyList<string> Modes,
    IReadOnlyList<ImageContractModeCase> Cases);

public sealed record ImageInputContractModeIndex(
    string Port,
    string Version,
    string EvidenceSummary,
    IReadOnlyList<ImageContractModeGroup> ModeGroups);

public static class ImageContractPresentationBuilder
{
    public const string LegacyCompatibilityNotice = "Legacy 8U compatibility allowance — unverified";

    public static ImageInputContractPresentation Build(ImageInputContract contract)
    {
        ArgumentNullException.ThrowIfNull(contract);

        var variants = contract.Variants ?? [];
        var verifiedSupport = variants.Count(item => item.Verification == ImageContractVerification.VerifiedSupport);
        var verifiedConversion = variants.Count(item => item.Verification == ImageContractVerification.VerifiedConversion);
        var compatibility = variants.Count(item => item.Verification == ImageContractVerification.LegacyCompatibilityAllowance);
        var verifiedRejection = variants.Count(item => item.Verification == ImageContractVerification.VerifiedRejection);
        var unknown = variants.Count(item => item.Verification == ImageContractVerification.Unknown);
        var allowed = variants.Count(item => item.Admission == ImageContractAdmission.Allowed);
        var hasProductionSupport = verifiedSupport + verifiedConversion > 0;
        var compatibilityOnly = compatibility > 0 && !hasProductionSupport;

        var groups = variants
            .GroupBy(item => new
            {
                item.Mode,
                item.Condition,
                item.Admission,
                item.Verification,
                item.ConversionPolicy,
                item.OutputDepthPolicy,
                item.DynamicRangePolicy,
                item.InputValuePolicy,
                item.FailureCode,
                item.EvidenceLevel
            })
            .OrderBy(group => group.Key.Mode, StringComparer.Ordinal)
            .ThenBy(group => group.Key.Condition, StringComparer.Ordinal)
            .ThenBy(group => group.Key.Admission)
            .ThenBy(group => group.Key.Verification)
            .Select(group => new ImageContractVariantPresentation(
                group.Key.Mode,
                group.Key.Condition,
                group.Key.Admission,
                group.Key.Verification,
                group
                    .OrderBy(item => GetDepthOrder(item.Depth))
                    .ThenBy(item => item.Channels)
                    .Select(item => FormatInputType(item.Depth, item.Channels))
                    .Distinct(StringComparer.Ordinal)
                    .ToArray(),
                group.Key.ConversionPolicy,
                group.Key.OutputDepthPolicy,
                group.Key.DynamicRangePolicy,
                group.Key.InputValuePolicy,
                group.Key.FailureCode,
                group.Key.EvidenceLevel))
            .ToArray();

        return new ImageInputContractPresentation(
            contract.InputPort,
            contract.ContractVersion,
            allowed,
            verifiedSupport,
            verifiedConversion,
            compatibility,
            verifiedRejection,
            unknown,
            hasProductionSupport,
            compatibilityOnly,
            BuildEvidenceSummary(hasProductionSupport, compatibilityOnly, compatibility, unknown),
            groups);
    }

    public static IReadOnlyList<ImageInputContractPresentation> Build(
        IEnumerable<ImageInputContract> contracts) =>
        contracts?.Select(Build).ToArray() ?? [];

    public static IReadOnlyList<ImageInputContractCompactPresentation> BuildCompact(
        IEnumerable<ImageInputContract> contracts) =>
        Build(contracts).Select(BuildCompact).ToArray();

    public static IReadOnlyList<ImageInputContractModeIndex> BuildModeIndex(
        IEnumerable<ImageInputContract> contracts) =>
        Build(contracts).Select(BuildModeIndex).ToArray();

    public static IReadOnlyList<ImageInputContractModeIndex> BuildModeIndex(
        IEnumerable<ImageInputContractPresentation> presentations) =>
        presentations?.Select(BuildModeIndex).ToArray() ?? [];

    public static IReadOnlyList<ImageInputContractCompactPresentation> BuildModeDetails(
        IEnumerable<ImageInputContract> contracts,
        string mode)
    {
        if (string.IsNullOrWhiteSpace(mode))
        {
            return BuildCompact(contracts);
        }

        return BuildCompact(contracts)
            .Select(contract => contract with
            {
                Variants = contract.Variants
                    .Where(group => group.Modes.Contains(mode, StringComparer.OrdinalIgnoreCase))
                    .Select(group => group with
                    {
                        Modes = group.Modes
                            .Where(value => value.Equals(mode, StringComparison.OrdinalIgnoreCase))
                            .ToArray()
                    })
                    .ToArray()
            })
            .Where(contract => contract.Variants.Count > 0)
            .ToArray();
    }

    public static ImageInputContractModeIndex BuildModeIndex(
        ImageInputContractPresentation presentation)
    {
        ArgumentNullException.ThrowIfNull(presentation);

        var casesByMode = presentation.ExactVariantGroups
            .GroupBy(group => group.Mode, StringComparer.Ordinal)
            .ToDictionary(
                group => group.Key,
                group => group
                    .Select(item => new ImageContractModeCase(
                        item.ExactInputTypes,
                        item.Admission,
                        item.Verification,
                        item.FailureCode,
                        item.EvidenceLevel))
                    .OrderBy(item => item.Admission)
                    .ThenBy(item => item.Verification)
                    .ThenBy(item => string.Join('\u001F', item.Inputs), StringComparer.Ordinal)
                    .ToArray(),
                StringComparer.Ordinal);

        var modeGroups = casesByMode
            .GroupBy(item => JsonSerializer.Serialize(item.Value))
            .OrderBy(group => group.Min(item => item.Key), StringComparer.Ordinal)
            .Select(group => new ImageContractModeGroup(
                group.Select(item => item.Key)
                    .OrderBy(value => value, StringComparer.Ordinal)
                    .ToArray(),
                group.First().Value))
            .ToArray();

        return new ImageInputContractModeIndex(
            presentation.InputPort,
            presentation.ContractVersion,
            presentation.EvidenceSummary,
            modeGroups);
    }

    public static ImageInputContractCompactPresentation BuildCompact(
        ImageInputContractPresentation presentation)
    {
        ArgumentNullException.ThrowIfNull(presentation);

        var groups = presentation.ExactVariantGroups
            .GroupBy(item => new
            {
                Inputs = string.Join('\u001F', item.ExactInputTypes),
                item.Condition,
                item.Admission,
                item.Verification,
                item.ConversionPolicy,
                item.OutputDepthPolicy,
                item.DynamicRangePolicy,
                item.InputValuePolicy,
                item.FailureCode,
                item.EvidenceLevel
            })
            .OrderBy(group => group.Min(item => item.Mode), StringComparer.Ordinal)
            .ThenBy(group => group.Key.Inputs, StringComparer.Ordinal)
            .Select(group => new ImageContractCompactVariantGroup(
                group.Select(item => item.Mode)
                    .Distinct(StringComparer.Ordinal)
                    .OrderBy(value => value, StringComparer.Ordinal)
                    .ToArray(),
                group.First().ExactInputTypes,
                group.Key.Condition,
                group.Key.Admission,
                group.Key.Verification,
                group.Key.ConversionPolicy,
                group.Key.OutputDepthPolicy,
                group.Key.DynamicRangePolicy,
                group.Key.InputValuePolicy,
                group.Key.FailureCode,
                group.Key.EvidenceLevel))
            .ToArray();

        return new ImageInputContractCompactPresentation(
            presentation.InputPort,
            presentation.ContractVersion,
            presentation.EvidenceSummary,
            presentation.VerifiedSupportVariantCount,
            presentation.VerifiedConversionVariantCount,
            presentation.LegacyCompatibilityVariantCount,
            presentation.VerifiedRejectionVariantCount,
            presentation.UnknownVariantCount,
            groups);
    }

    public static OperatorImageContractPresentationSummary Summarize(
        IEnumerable<ImageInputContract> contracts)
    {
        var presentations = Build(contracts);
        var verifiedSupport = presentations.Sum(item => item.VerifiedSupportVariantCount);
        var verifiedConversion = presentations.Sum(item => item.VerifiedConversionVariantCount);
        var compatibility = presentations.Sum(item => item.LegacyCompatibilityVariantCount);
        var unknown = presentations.Sum(item => item.UnknownVariantCount);
        var hasProductionSupport = verifiedSupport + verifiedConversion > 0;
        var compatibilityOnly = compatibility > 0 && !hasProductionSupport;

        return new OperatorImageContractPresentationSummary(
            presentations.Count,
            presentations.Sum(item => item.AllowedVariantCount),
            verifiedSupport,
            verifiedConversion,
            compatibility,
            presentations.Sum(item => item.VerifiedRejectionVariantCount),
            unknown,
            hasProductionSupport,
            compatibilityOnly,
            BuildEvidenceSummary(hasProductionSupport, compatibilityOnly, compatibility, unknown));
    }

    public static bool IsDefaultAiRecommendation(
        OperatorLifecycle lifecycle,
        IEnumerable<ImageInputContract> contracts)
    {
        if (!OperatorLifecyclePolicy.IsDefaultAiRecommendation(lifecycle))
        {
            return false;
        }

        var summary = Summarize(contracts);
        return summary.ContractCount == 0 || summary.HasProductionSupport;
    }

    public static bool RequiresAiDisclosure(
        OperatorLifecycle lifecycle,
        IEnumerable<ImageInputContract> contracts)
    {
        if (OperatorLifecyclePolicy.RequiresDisclosure(lifecycle))
        {
            return true;
        }

        var summary = Summarize(contracts);
        return summary.ContractCount > 0 &&
               (summary.LegacyCompatibilityVariantCount > 0 ||
                summary.UnknownVariantCount > 0 ||
                !summary.HasProductionSupport);
    }

    public static string FormatInputType(string depth, int channels) => $"{depth}C{channels}";

    private static string BuildEvidenceSummary(
        bool hasProductionSupport,
        bool compatibilityOnly,
        int compatibilityCount,
        int unknownCount)
    {
        if (compatibilityOnly)
        {
            return LegacyCompatibilityNotice;
        }

        if (hasProductionSupport && compatibilityCount > 0)
        {
            return $"Verified production support is present; {LegacyCompatibilityNotice}.";
        }

        if (hasProductionSupport)
        {
            return "Verified production support is present.";
        }

        return unknownCount > 0
            ? "Unknown — no verified executable image support is registered."
            : "No executable image support is admitted.";
    }

    private static int GetDepthOrder(string depth) => depth switch
    {
        "CV_8U" => 0,
        "CV_8S" => 1,
        "CV_16U" => 2,
        "CV_16S" => 3,
        "CV_32S" => 4,
        "CV_32F" => 5,
        "CV_64F" => 6,
        _ => int.MaxValue
    };
}

#pragma warning disable CS0618
internal static class ImageContractCompatibilityAdapter
{
    public static IReadOnlyList<ImageContractVariant> ToExactVariants(
        IReadOnlyList<string> supportedDepths,
        IReadOnlyList<int> supportedChannels,
        IReadOnlyList<ImageModeRestriction> modeRestrictions,
        ImageContractStatus status,
        string conversionPolicy,
        string outputDepthPolicy,
        string dynamicRangePolicy,
        string failureCode,
        string evidenceLevel)
    {
        var restrictions = modeRestrictions is { Count: > 0 }
            ? modeRestrictions
            :
            [
                new ImageModeRestriction(
                    "Default",
                    status,
                    supportedDepths,
                    supportedChannels,
                    conversionPolicy,
                    outputDepthPolicy,
                    dynamicRangePolicy,
                    failureCode,
                    evidenceLevel,
                    "Legacy compatibility contract")
            ];

        return restrictions
            .SelectMany(rule => rule.SupportedDepths.SelectMany(depth =>
                rule.SupportedChannels.Select(channels =>
                {
                    var (admission, verification) = Map(rule.Status, rule.EvidenceLevel);
                    return new ImageContractVariant(
                        rule.Mode,
                        depth,
                        channels,
                        string.IsNullOrWhiteSpace(rule.Condition) ? "Legacy compatibility contract" : rule.Condition,
                        admission,
                        verification,
                        rule.ConversionPolicy,
                        rule.OutputDepthPolicy,
                        rule.DynamicRangePolicy,
                        ImageContractInputValuePolicy.Any,
                        rule.FailureCode,
                        rule.EvidenceLevel);
                })))
            .ToArray();
    }

    public static ImageContractStatus GetLegacyStatus(IReadOnlyList<ImageContractVariant> variants)
    {
        if (variants.Any(item => item.Verification == ImageContractVerification.VerifiedConversion))
            return ImageContractStatus.Converted;
        if (variants.Any(item => item.Verification == ImageContractVerification.VerifiedSupport))
            return ImageContractStatus.Native;
        if (variants.Any(item => item.Verification == ImageContractVerification.LegacyCompatibilityAllowance))
            return ImageContractStatus.Restricted;
        if (variants.Count > 0 && variants.All(item => item.Admission == ImageContractAdmission.Rejected))
            return ImageContractStatus.Rejected;
        return ImageContractStatus.Unknown;
    }

    public static IReadOnlyList<ImageModeRestriction> GetLegacyRestrictions(
        IReadOnlyList<ImageContractVariant> variants) =>
        variants.Select(item => new ImageModeRestriction(
            item.Mode,
            GetLegacyStatus([item]),
            [item.Depth],
            [item.Channels],
            item.ConversionPolicy,
            item.OutputDepthPolicy,
            item.DynamicRangePolicy,
            item.FailureCode,
            item.EvidenceLevel,
            item.Condition)).ToArray();

    public static string GetLegacyEvidenceLevel(IReadOnlyList<ImageContractVariant> variants)
    {
        var levels = variants.Select(item => item.EvidenceLevel)
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        return levels.Length == 1 ? levels[0] : "Mixed";
    }

    private static (ImageContractAdmission Admission, ImageContractVerification Verification) Map(
        ImageContractStatus status,
        string evidenceLevel) => status switch
    {
        ImageContractStatus.Native =>
            (ImageContractAdmission.Allowed, ImageContractVerification.VerifiedSupport),
        ImageContractStatus.Converted =>
            (ImageContractAdmission.Allowed, ImageContractVerification.VerifiedConversion),
        ImageContractStatus.Restricted when evidenceLevel.StartsWith("E0", StringComparison.OrdinalIgnoreCase) =>
            (ImageContractAdmission.Allowed, ImageContractVerification.LegacyCompatibilityAllowance),
        ImageContractStatus.Rejected =>
            (ImageContractAdmission.Rejected, ImageContractVerification.VerifiedRejection),
        _ => (ImageContractAdmission.Unknown, ImageContractVerification.Unknown)
    };
}
#pragma warning restore CS0618

public interface IOperatorImageContractProvider
{
    IReadOnlyList<ImageInputContract> GetContracts(
        OperatorType operatorType,
        IReadOnlyList<string> imageInputPorts,
        OperatorLifecycle lifecycle);
}

/// <summary>
/// Resolves image contracts from the same provider for scanner and runtime use.
/// Operators without a dedicated provider receive a conservative Stage 2 contract:
/// legacy 8U execution remains available, while higher depths are rejected until
/// operator-specific evidence promotes them.
/// </summary>
public static class OperatorImageContractResolver
{
    public const string ContractVersion = "2.1";

    private static readonly string[] StandardDepths =
        ["CV_8U", "CV_8S", "CV_16U", "CV_16S", "CV_32S", "CV_32F", "CV_64F"];

    public static IReadOnlyList<ImageInputContract> Resolve(
        Type operatorClrType,
        OperatorType operatorType)
    {
        ArgumentNullException.ThrowIfNull(operatorClrType);

        var imagePorts = operatorClrType
            .GetCustomAttributes<InputPortAttribute>(inherit: false)
            .Where(attribute => attribute.DataType == PortDataType.Image)
            .Select(attribute => attribute.Name)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (imagePorts.Length == 0)
        {
            return [];
        }

        var lifecycle = operatorClrType
            .GetCustomAttribute<OperatorMetaAttribute>(inherit: false)?
            .Lifecycle ?? OperatorLifecycle.Stable;
        var providerAttribute = operatorClrType
            .GetCustomAttribute<OperatorImageContractProviderAttribute>(inherit: false);
        if (providerAttribute is not null)
        {
            if (!typeof(IOperatorImageContractProvider).IsAssignableFrom(providerAttribute.ProviderType))
            {
                throw new InvalidOperationException(
                    $"Image contract provider '{providerAttribute.ProviderType.FullName}' for '{operatorClrType.FullName}' " +
                    $"must implement {nameof(IOperatorImageContractProvider)}.");
            }

            if (Activator.CreateInstance(providerAttribute.ProviderType) is not IOperatorImageContractProvider provider)
            {
                throw new InvalidOperationException(
                    $"Image contract provider '{providerAttribute.ProviderType.FullName}' could not be created.");
            }

            var resolved = provider.GetContracts(operatorType, imagePorts, lifecycle)
                .Where(contract => contract is not null)
                .ToArray();
            ValidateResolvedContracts(operatorClrType, imagePorts, resolved);
            return resolved;
        }

        var defaults = imagePorts
            .Select(port => CreateConservativeDefault(port, lifecycle))
            .ToArray();
        ValidateResolvedContracts(operatorClrType, imagePorts, defaults);
        return defaults;
    }

    public static ImageInputContract CreateConservativeDefault(
        string inputPort,
        OperatorLifecycle lifecycle)
    {
        var isExperimental = lifecycle == OperatorLifecycle.Experimental;
        var variants = CreateConservativeDefaultVariants(isExperimental);
        return new ImageInputContract(
            inputPort,
            isExperimental ? [] : ["CV_8U"],
            isExperimental ? [] : [1, 3, 4],
            isExperimental ? [] : ["CV_8U"],
            isExperimental
                ? "Unverified image depth domain; Unknown is not support."
                : "Legacy 8U compatibility allowance — unverified. Higher-depth and undeclared combinations remain Unknown and fail closed.",
            "None",
            "Operator-specific legacy output policy; no Stage 2 depth widening.",
            isExperimental
                ? "Undefined until verified."
                : "8-bit native numeric domain; no implicit MinMax conversion.",
            variants,
            isExperimental ? "Unknown" : "NotApplicableFor8U",
            "IMAGE_DEPTH_UNSUPPORTED",
            ContractVersion);
    }

    private static IReadOnlyList<ImageContractVariant> CreateConservativeDefaultVariants(bool isExperimental)
    {
        var variants = new List<ImageContractVariant>();
        foreach (var depth in StandardDepths)
        {
            foreach (var channels in new[] { 1, 2, 3, 4 })
            {
                var isLegacyAllowance = !isExperimental &&
                                        depth == "CV_8U" &&
                                        channels is 1 or 3 or 4;
                variants.Add(new ImageContractVariant(
                    "Default",
                    depth,
                    channels,
                    isLegacyAllowance
                        ? "Legacy 8U execution path retained for compatibility; no per-operator E2 evidence."
                        : "No operator-specific executable evidence is registered.",
                    isLegacyAllowance ? ImageContractAdmission.Allowed : ImageContractAdmission.Unknown,
                    isLegacyAllowance
                        ? ImageContractVerification.LegacyCompatibilityAllowance
                        : ImageContractVerification.Unknown,
                    "None",
                    "Operator-specific legacy output policy; no Stage 2 depth widening.",
                    isLegacyAllowance ? "8-bit legacy numeric domain." : "Undefined until verified.",
                    ImageContractInputValuePolicy.Any,
                    isLegacyAllowance ? "IMAGE_DEPTH_UNSUPPORTED" : "IMAGE_CONTRACT_UNKNOWN",
                    isLegacyAllowance ? "E0_SOURCE_AUDIT" : "Unknown"));
            }
        }

        return variants;
    }

    private static void ValidateResolvedContracts(
        Type operatorClrType,
        IReadOnlyList<string> imagePorts,
        IReadOnlyList<ImageInputContract> contracts)
    {
        var declaredPorts = imagePorts.ToHashSet(StringComparer.Ordinal);
        var contractPorts = contracts.Select(contract => contract.InputPort).ToList();
        contractPorts.ShouldContainEachDeclaredPort(operatorClrType, declaredPorts);

        foreach (var contract in contracts)
        {
            if (!declaredPorts.Contains(contract.InputPort))
            {
                throw new InvalidOperationException(
                    $"Image contract for '{operatorClrType.FullName}' references undeclared input port '{contract.InputPort}'.");
            }

            if (string.IsNullOrWhiteSpace(contract.ContractVersion) ||
                string.IsNullOrWhiteSpace(contract.FailureCode) ||
                contract.Variants.Count == 0)
            {
                throw new InvalidOperationException(
                    $"Image contract for '{operatorClrType.FullName}:{contract.InputPort}' is incomplete.");
            }

            ValidateVariants(operatorClrType, contract);
        }
    }

    private static void ValidateVariants(Type operatorClrType, ImageInputContract contract)
    {
        var duplicate = contract.Variants
            .GroupBy(variant => (variant.Mode, variant.Depth, variant.Channels))
            .FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null)
        {
            throw new InvalidOperationException(
                $"Image contract for '{operatorClrType.FullName}:{contract.InputPort}' contains duplicate exact variant " +
                $"Mode={duplicate.Key.Mode}, Depth={duplicate.Key.Depth}, Channels={duplicate.Key.Channels}.");
        }

        foreach (var variant in contract.Variants)
        {
            if (string.IsNullOrWhiteSpace(variant.Mode) ||
                string.IsNullOrWhiteSpace(variant.Depth) ||
                variant.Channels <= 0 ||
                string.IsNullOrWhiteSpace(variant.Condition) ||
                string.IsNullOrWhiteSpace(variant.FailureCode) ||
                string.IsNullOrWhiteSpace(variant.EvidenceLevel))
            {
                throw new InvalidOperationException(
                    $"Image contract variant for '{operatorClrType.FullName}:{contract.InputPort}' is incomplete.");
            }

            var verificationMatchesAdmission = variant.Admission switch
            {
                ImageContractAdmission.Allowed => variant.Verification is
                    ImageContractVerification.VerifiedSupport or
                    ImageContractVerification.VerifiedConversion or
                    ImageContractVerification.LegacyCompatibilityAllowance,
                ImageContractAdmission.Rejected =>
                    variant.Verification == ImageContractVerification.VerifiedRejection,
                ImageContractAdmission.Unknown =>
                    variant.Verification == ImageContractVerification.Unknown,
                _ => false
            };
            if (!verificationMatchesAdmission)
            {
                throw new InvalidOperationException(
                    $"Image contract variant for '{operatorClrType.FullName}:{contract.InputPort}' has inconsistent " +
                    $"Admission={variant.Admission} and Verification={variant.Verification}.");
            }

            if (variant.EvidenceLevel.StartsWith("E0", StringComparison.OrdinalIgnoreCase) &&
                variant.Verification != ImageContractVerification.LegacyCompatibilityAllowance)
            {
                throw new InvalidOperationException(
                    $"E0 image evidence for '{operatorClrType.FullName}:{contract.InputPort}' may only describe an unverified legacy compatibility allowance.");
            }
        }

        var allowed = contract.Variants
            .Where(variant => variant.Admission == ImageContractAdmission.Allowed)
            .ToArray();
        var summaryDepths = allowed.Select(variant => variant.Depth)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(value => value, StringComparer.Ordinal)
            .ToArray();
        var summaryChannels = allowed.Select(variant => variant.Channels)
            .Distinct()
            .OrderBy(value => value)
            .ToArray();
        if (!summaryDepths.SequenceEqual(contract.SupportedDepths.OrderBy(value => value, StringComparer.Ordinal), StringComparer.Ordinal) ||
            !summaryChannels.SequenceEqual(contract.SupportedChannels.OrderBy(value => value)))
        {
            throw new InvalidOperationException(
                $"Image contract summaries for '{operatorClrType.FullName}:{contract.InputPort}' do not match its allowed exact variants.");
        }
    }

    private static void ShouldContainEachDeclaredPort(
        this IReadOnlyCollection<string> contractPorts,
        Type operatorClrType,
        IReadOnlySet<string> declaredPorts)
    {
        foreach (var port in declaredPorts)
        {
            if (!contractPorts.Contains(port, StringComparer.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Image contract provider for '{operatorClrType.FullName}' did not describe input port '{port}'.");
            }
        }
    }
}
