<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>ClearVision.Product.Core</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ClearVision.Product.Contracts\ClearVision.Product.Contracts.csproj" />
  </ItemGroup>
</Project>
