// <auto-generated />
using System;
using ClearVision.Product.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClearVision.Product.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VisionDbContext))]
    partial class VisionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ClearVision.Product.Core.Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnotationData")
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<Guid>("InspectionResultId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InspectionResultId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.InspectionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationBundleId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExecutionOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasJudgmentSignal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowVersionHash")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DecisionOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionSource")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectionTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDataJson")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("OutputImage")
                        .HasColumnType("BLOB");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionTime");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("InspectionResults");
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.OperatorFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Flow_CreatedAt");

                    b.Property<string>("DecisionConfiguration")
                        .HasColumnType("TEXT")
                        .HasColumnName("Flow_DecisionConfiguration");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Flow_IsDeleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Flow_ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Flow_Name");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("PersistenceRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastOpenedAt");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationAlarmEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlarmId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId")
                        .IsUnique();

                    b.HasIndex("StationId", "IsActive");

                    b.ToTable("StationAlarmEvents");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationAuditRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetStationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditId")
                        .IsUnique();

                    b.HasIndex("TargetStationId", "CreatedAtUtc");

                    b.ToTable("StationAuditRecords");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationCommandRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("StationId", "CreatedAtUtc");

                    b.HasIndex("StationId", "Status");

                    b.ToTable("StationCommandRecords");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationConnectionEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "CreatedAtUtc");

                    b.ToTable("StationConnectionEvents");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationHealthSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraStatusSummary")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPackageHealth")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPackageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiskFreeMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskTotalMb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlcStatusSummary")
                        .HasColumnType("TEXT");

                    b.Property<long>("PrivateMemoryMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessUptimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpoolBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpoolPendingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkingSetMb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "CreatedAtUtc");

                    b.HasIndex("StationId", "SequenceId")
                        .IsUnique();

                    b.ToTable("StationHealthSnapshots");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationLogSummaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "SequenceId")
                        .IsUnique();

                    b.HasIndex("StationId", "TimestampUtc");

                    b.ToTable("StationLogSummaries");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationNodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraAlias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPackageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPackageVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionNodeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddressHint")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddressHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkcellName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("StationNodes");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationPackageRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Production");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("StationPackageRecords");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationResultSummaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryOutputsPreviewJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("StationId", "CompletedAtUtc");

                    b.HasIndex("StationId", "SequenceId")
                        .IsUnique();

                    b.ToTable("StationResultSummaries");
                });

            modelBuilder.Entity("ClearVision.Product.Infrastructure.Data.StationSyncCursorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastPersistedSequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReceivedHealthSequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReceivedLogSequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("StationSyncCursors");
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.Defect", b =>
                {
                    b.HasOne("ClearVision.Product.Core.Entities.InspectionResult", null)
                        .WithMany("Defects")
                        .HasForeignKey("InspectionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.Operator", b =>
                {
                    b.HasOne("ClearVision.Product.Core.Entities.OperatorFlow", null)
                        .WithMany("Operators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ClearVision.Product.Core.ValueObjects.Port", "InputPorts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<int>("DataType")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Direction")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("OperatorId");

                            b1.ToTable("Operators_InputPorts");

                            b1.WithOwner()
                                .HasForeignKey("OperatorId");
                        });

                    b.OwnsMany("ClearVision.Product.Core.ValueObjects.Port", "OutputPorts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<int>("DataType")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Direction")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("OperatorId");

                            b1.ToTable("Operators_OutputPorts");

                            b1.WithOwner()
                                .HasForeignKey("OperatorId");
                        });

                    b.OwnsMany("ClearVision.Product.Core.ValueObjects.Parameter", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DataType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DefaultValueJson")
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MaxValueJson")
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("MinValueJson")
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ValueJson")
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("OperatorId");

                            b1.ToTable("Parameter");

                            b1.WithOwner()
                                .HasForeignKey("OperatorId");
                        });

                    b.OwnsOne("ClearVision.Product.Core.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("X")
                                .HasColumnType("REAL")
                                .HasColumnName("PositionX");

                            b1.Property<double>("Y")
                                .HasColumnType("REAL")
                                .HasColumnName("PositionY");

                            b1.HasKey("OperatorId");

                            b1.ToTable("Operators");

                            b1.WithOwner()
                                .HasForeignKey("OperatorId");
                        });

                    b.Navigation("InputPorts");

                    b.Navigation("OutputPorts");

                    b.Navigation("Parameters");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.OperatorFlow", b =>
                {
                    b.HasOne("ClearVision.Product.Core.Entities.Project", null)
                        .WithOne("Flow")
                        .HasForeignKey("ClearVision.Product.Core.Entities.OperatorFlow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ClearVision.Product.Core.ValueObjects.OperatorConnection", "Connections", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OperatorFlowId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("SourceOperatorId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("SourcePortId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TargetOperatorId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TargetPortId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("OperatorFlowId");

                            b1.ToTable("OperatorConnection");

                            b1.WithOwner()
                                .HasForeignKey("OperatorFlowId");
                        });

                    b.Navigation("Connections");
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.InspectionResult", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.OperatorFlow", b =>
                {
                    b.Navigation("Operators");
                });

            modelBuilder.Entity("ClearVision.Product.Core.Entities.Project", b =>
                {
                    b.Navigation("Flow")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
