<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>ClearVision.Product.Station.Simulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClearVision.Product.Runtime.Abstractions\ClearVision.Product.Runtime.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

</Project>
